[package]
name = "img2text_web"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "= 0.2.67"
wasm-logger = { version = "0.2" }
js-sys = { version = "0.3.44" }
serde = { version = "1.0.123" }
yew = { version = "0.17" }

[dependencies.web-sys]
version = "0.3.44"
features = [
    "Window",
]
